version : "3.9"

services:
  web:
    build: .
    container_name: expense-tracker
    ports:
      - "80:80"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST_CONTAINER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TOKEN_DURATION: ${TOKEN_DURATION}
      TOKEN_SECRET: ${TOKEN_SECRET}
    depends_on:
      - db 

  db:
    image: postgres:15-alpine
    container_name: postges-db 
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
