"""backfilling expense category

Revision ID: 772709c55bd3
Revises: a9a513e2cb34
Create Date: 2025-06-15 11:50:56.650932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '772709c55bd3'
down_revision: Union[str, None] = 'a9a513e2cb34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
               INSERT INTO expenses (finance_id, type)
               SELECT finances.id, 'miscellaneous'
               FROM finances
               LEFT JOIN expenses ON finances.id = expenses.finance_id
               WHERE expenses.id IS NULL

        """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
