"""upgraded expense category

Revision ID: a9a513e2cb34
Revises: 41e4b252233e
Create Date: 2025-06-13 20:41:39.200930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a513e2cb34'
down_revision: Union[str, None] = '41e4b252233e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"ALTER TYPE expensescategory ADD VALUE 'miscellaneous'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
